[package]
name = "rat_web_credential_encryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = { version = "0.13", features = ["ecdh"] }
aes-gcm = "0.10"
base64ct = { version = "1.6", features = ["alloc"] }
rand_core = "0.6"
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
